##
## This file is part of the libopencm3 project.
##
## Copyright (C) 2015 Chuck McManis <cmcmanis@mcmanis.com>
##
## This library is free software: you can redistribute it and/or modify
## it under the terms of the GNU Lesser General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public License
## along with this library.  If not, see <http://www.gnu.org/licenses/>.
##

BINARY = main

OPENCM3_DIR=/usr/local/arm-none-eabi
LDSCRIPT = ./nucleo-f401re.ld

OBJS = delay.o st7783.o touch.o usart.o comm.o fattime.o ff_test_term.o rtc.o term_io.o
include ./Makefile.include
